# Generated by Django 4.2.7 on 2025-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careercast',
            name='teleprompter_text',
        ),
        migrations.AlterField(
            model_name='careercast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='careercast',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='career_casts/resumes/'),
        ),
        migrations.AlterField(
            model_name='careercast',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='career_casts/videos/'),
        ),
    ]
