# Generated by Django 4.2.7 on 2025-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_careercast_teleprompter_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercast',
            name='teleprompter_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
